// src/views/Login.vue
<template>
  <div class="form-header-custom-color"><h2>LOGIN</h2></div>
  <form
    novalidate
    class="form-main form-main-border"
    @submit.prevent="handleSubmit"
  >
    <div class="mb-3">
      <label class="form-label" for="formGroupEmail">Email</label>
      <input
        name="email"
        placeholder="Email"
        type="email"
        id="formGroupEmail"
        class="form-control"
        v-model="email"
      />
    </div>
    <div class="mb-3">
      <label class="form-label" for="formGroupPassword">Password</label>
      <input
        name="password"
        placeholder="Password"
        type="password"
        id="formGroupPassword"
        class="form-control"
        v-model="password"
      />
    </div>
    <div class="d-grid">
      <button type="submit" class="btn-custom-color btn btn-outline-danger">
        LOGIN
      </button>
    </div>
  </form>
  <div class="d-flex align-items-end flex-column">
    <RouterLink class="no-side-padding btn btn-link" to="/register"
      >Join Us!</RouterLink
    >
    <RouterLink class="no-side-padding btn btn-link" to="/forgot-password"
      >Forgot Password</RouterLink
    >
    <RouterLink class="no-side-padding btn btn-link" to="/verification"
      >Verification</RouterLink
    >
  </div>
  <Spinner :show="showSpinner" />
  <template v-if="toastMessage">
    <Toast :message="toastMessage" />
  </template>
</template>

<script>
import { RouterLink } from "vue-router";
import router from "../router";
import UserApiService from "../services/user";
import Spinner from "../common/Spinner.vue";
import Toast from "../common/Toast.vue";

export default {
  name: "LoginPage",
  components: {
    RouterLink,
    Spinner,
    Toast,
  },
  data() {
    return {
      email: "",
      password: "",
      showSpinner: false,
      toastMessage: "",
    };
  },
  methods: {
    async handleSubmit() {
      this.showSpinner = true;
      this.toastMessage = "";
      const formData = { email: this.email, password: this.password };
      await UserApiService.login(formData)
        .then((response) => {
          const { data } = response.data;
          // Set auth token
          const auth = data ? JSON.stringify(data) : null;
          localStorage.setItem("auth-info", auth);
          router.push("/home");
        })
        .catch(({ response }) => {
          this.showSpinner = false;
          if (response?.status === 401) {
            localStorage.setItem("auth-info", "");
            router.push("/unauthorized");
          } else {
            const message = response?.error
              ? response.error?.message
              : response?.data.message;
            this.toastMessage = message;
          }
        })
        .finally(() => (this.showSpinner = false));
    },
  },
};
</script>

<style scoped>
.form-main {
  padding: 20px;
}

.form-main-border {
  border: solid 1px;
  border-radius: 10px;
}

.form-header-custom-color {
  color: #9d1919;
}

.btn-custom-color {
  --bs-btn-color: #9d1919;
  --bs-btn-border-color: #9d1919;
  --bs-btn-hover-bg: #9d1919;
  --bs-btn-hover-border-color: #9d1919;
}

.no-side-padding {
  padding-left: 0;
  padding-right: 0;
}
</style>

// src/app/features/login/login.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { FormGroup, FormControl } from '@angular/forms';
import { HttpParams } from '@angular/common/http';
import { UsersService } from 'src/app/api/users.service';
import { UserRoles } from 'src/app/constants/user.role';
import { SpinnerService } from 'src/app/common/spinner/spinner.service';
import { ToastService } from 'src/app/common/toast/toast.service';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})

export class LoginComponent {
  loginEvent: any;

  loginForm = new FormGroup({
    email: new FormControl(''),
    password: new FormControl('')
  });

  constructor(
    private usersService: UsersService,
    private spinnerService: SpinnerService,
    private toastService: ToastService,
    private router: Router
  ) {}

  handleSubmit() {
    this.spinnerService.show();
    const { email, password } = this.loginForm.value;
    const formData = new HttpParams()
      .set('email', email || '')
      .set('password', password || '');

    this.loginEvent = this.usersService.login(formData)
      .subscribe({
        next: response => {
          const { data } = response;
          if (data.role !== UserRoles.REPORTER) {
            localStorage.setItem('auth-info', '');
            this.router.navigate(['/unauthorized']);
          } else {
            const auth = data ? JSON.stringify(data) : '';
            localStorage.setItem('auth-info', auth);
            this.router.navigate(['/unpublished']);
          }
        },
        error: response => {
          this.spinnerService.hide();
          if (response?.status === 401) {
            localStorage.setItem('auth-info', '');
            this.router.navigate(['/unauthorized']);
          } else {
            this.toastService.show(response.error?.message);
          }
        },
        complete: () => this.spinnerService.hide()
      });
  };

  ngOnDestroy() {
    if (this.loginEvent) {
      this.loginEvent.unsubscribe();
    }
  }
}
<div class="form-header-custom-color"><h2>LOGIN</h2></div>
<form
  novalidate
  class="form-main form-main-border"
  [formGroup]="loginForm"
  (ngSubmit)="handleSubmit()"
>
  <div class="mb-3">
    <label class="form-label" for="formGroupEmail">Email</label
    ><input
      name="email"
      placeholder="Email"
      type="email"
      id="formGroupEmail"
      class="form-control"
      formControlName="email"
    />
  </div>
  <div class="mb-3">
    <label class="form-label" for="formGroupPassword">Password</label
    ><input
      name="password"
      placeholder="Password"
      type="password"
      id="formGroupPassword"
      class="form-control"
      formControlName="password"
    />
  </div>
  <div class="d-grid">
    <button type="submit" class="btn-custom-color btn btn-outline-danger">
      LOGIN
    </button>
  </div>
</form>
<div class="d-flex align-items-end flex-column">
  <a
    role="button"
    tabindex="0"
    routerLink="/forgot-password"
    class="no-side-padding btn btn-link"
    >Forgot Password</a
  ><a
    role="button"
    tabindex="0"
    routerLink="/verification"
    class="no-side-padding btn btn-link"
    >Verification</a
  >
</div>
